name: build_tests
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Run tox build tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          python-version: 3.8
          activate-environment: testenv
          channels: conda-forge
      - name: Setup conda python environments
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install -q -c conda-forge tox
          conda create -q -n py39 python=3.9
          conda create -q -n py310 python=3.10
      - name: Run pytest
        env:
          TOXENV: py38,py39,py310
        run: |
          export PY39_PATH=$CONDA/envs/py39/bin
          export PY310_PATH=$CONDA/envs/py310/bin
          export PATH=$PATH:$PY39_PATH:$PY310_PATH
          tox
      - name: Run code checks
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          TOXENV: typing,pypi-description,manifest,precom
        run: tox
